"""Mirrors every .md file under curriculum/, projects/, capstones/, cheatsheets/,
papers/, and system-design/ into docs/ as a thin `{% include-markdown %}`
wrapper, so `mkdocs build` serves the whole repo's content with no duplicated
prose (the wrapper just includes the real file). Regenerated by `make docs` and
`make docs-serve` every time -- the generated files under docs/ (outside the
handful of hand-written root wrappers) are gitignored.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_DIR = REPO_ROOT / "docs"

SOURCE_DIRS = ["curriculum", "projects", "capstones", "cheatsheets", "papers", "system-design"]
EXCLUDE_DIR_NAMES = {"starter", "solution", "tests", "examples", "__pycache__"}


def iter_source_files() -> list[Path]:
    files = []
    for source_dir in SOURCE_DIRS:
        base = REPO_ROOT / source_dir
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.md")):
            if any(part in EXCLUDE_DIR_NAMES for part in path.relative_to(base).parts[:-1]):
                continue
            files.append(path)
    return files


def main() -> None:
    written = 0
    for source_path in iter_source_files():
        rel = source_path.relative_to(REPO_ROOT)
        target_path = DOCS_DIR / rel
        target_path.parent.mkdir(parents=True, exist_ok=True)
        depth = len(rel.parts)
        include_path = "../" * depth + str(rel).replace("\\", "/")
        target_path.write_text(f'{{% include-markdown "{include_path}" %}}\n')
        written += 1
    print(f"Wrote {written} docs wrapper page(s) under {DOCS_DIR.relative_to(REPO_ROOT)}/")


if __name__ == "__main__":
    main()
